### ISSUE TITLE
Why do you minus 0.5?

### ISSUE THREAD

**Issue by liliangqi** [taokong/FoveaBox#1]
Hi, thanks for your work first. I would like to know why should we minus 0.5 when calculatethe positive area on the feature map as [here](https://github.com/taokong/FoveaBox/blob/master/mmdet/models/anchor_heads/fovea_head.py#L281)

**Comment by taokong** [comment]
Thanks for your question. It is correct, since numbers in  gt_bboxes are with float type.  We minus 0.5 and use ceil/floor to get  the  correct boxes in feature maps.
