### ISSUE TITLE
imprt error for mccv

### ISSUE THREAD

**Issue by Outlande** [taokong/FoveaBox#10]
When I want to train the Foveabox, there are an import error shows:

ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils' (/home/mmy/anaconda3/envs/foveabox/lib/python3.7/site-packages/mmcv/runner/utils.py)

I just install the mccv with " pip install -e -v . " as shown in "install.md". The version of mccv is 0.2.15, and pytorch is 1.1.0. I have seen mmcv/runner/utils.py. There are only three funtion get_host_info(), get_time_str(), obj_from_dict() instead of get_dist_info(). I have also tried installing mccv from source code, but it don't work either.

I really don't know how to fix it. can you give me a hand?

**Comment by Outlande** [comment]
The error shows in terminal
![1203984745](https://user-images.githubusercontent.com/48147430/71592387-f975dc00-2b6a-11ea-902a-a44500012c01.jpg)

**Comment by taokong** [comment]
maybe it is mmcv's version problem, you can directly try FoveaBox though the latest mmdetection 'https://github.com/open-mmlab/mmdetection/tree/master/configs/foveabox'

**Comment by Outlande** [comment]
> maybe it is mmcv's version problem, you can directly try FoveaBox though the latest mmdetection 'https://github.com/open-mmlab/mmdetection/tree/master/configs/foveabox'

OK, Thanks for your suggestion
