### ISSUE TITLE
Why only one sigma used?

### ISSUE THREAD

**Issue by zym1119** [taokong/FoveaBox#2]
I have some confusion about the code.

in origin paper, two sigma is used to generate R_pos and R_neg separately, and the area between R_neg and R_pos is unassigned and will be ignored during training, is my understanding correct?

but you use one one sigma to generate R_pos, i wonder this because of the implementation of focal loss in mmdetection does not support ignore_index, is that right?

thanks for answering

**Comment by taokong** [comment]
It is easy to ignore target using pytorch.  The reason is one sigma is more simple and easy to tune.

**Comment by taokong** [comment]
closed
