### ISSUE TITLE
inference_demo.ipynb doesn't work

### ISSUE THREAD

**Issue by buus2** [taokong/FoveaBox#3]
Hi,

Notebook `demo/inference_demo.ipynb` doesn't work. It needs the structure of the config file as it is in mmdetection repo. More precisely, it needs `model.data.test.pipeline` key which does not exist in the FoveaBox's version of the config files.

**Comment by buus2** [comment]
OK, I found the reason. Instruction https://github.com/taokong/FoveaBox/blob/master/INSTALL.md#install-mmdetection is misleading. We should use `setup.py` from `FoveaBox`, not from `mmdetection` repo.
Cheers

**Comment by taokong** [comment]
resolved
