### ISSUE TITLE
when i run test.py, i meet a mistake,

### ISSUE THREAD

**Issue by leavewave** [taokong/FoveaBox#4]
![image](https://user-images.githubusercontent.com/41049484/64514344-08672300-d31d-11e9-9fe5-dc2031a05da6.png)
but i enter the python,
and import mmdet, it has model mmdet
![image](https://user-images.githubusercontent.com/41049484/64514424-29c80f00-d31d-11e9-9b93-6a49ae148fd1.png)

**Comment by taokong** [comment]
@leavewave Have you installed the repo according to https://github.com/taokong/FoveaBox/blob/master/INSTALL.md ?

**Comment by leavewave** [comment]
> @leavewave Have you installed the repo according to https://github.com/taokong/FoveaBox/blob/master/INSTALL.md ?

yeah, i installed according to this , but finally it report error like this?
![image](https://user-images.githubusercontent.com/41049484/64517950-db6a3e80-d323-11e9-8e4d-c7f833492c70.png)

**Comment by taokong** [comment]
That is because you have not installed the mmdet successfully.  Please check the CUDA environment and see if the libraries are correctly installed and can be found in system paths.

**Comment by taokong** [comment]
Try this:
export CUDA_HOME=/usr/local/cuda
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/cuda/lib64"

**Comment by leavewave** [comment]
> Try this:
> export CUDA_HOME=/usr/local/cuda
> export PATH="/usr/local/cuda/bin:$PATH"
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
> export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/cuda/lib64"

Thanks for your reply, I installed it successfully.Great skill!

**Comment by taokong** [comment]
@leavewave closed. If you still have problems in installing, just reopen the issue
