### ISSUE TITLE
复现实验精度

### ISSUE THREAD

**Issue by Hshuqin** [taokong/FoveaBox#6]
您好，我想请教您一下，直接根据您提供的代码，可以复现实验精度吗？（我复现后，还差差不多4个点，不知道是不是我哪里给漏了）

**Comment by taokong** [comment]
Sure, you can repreduce the performance. We have experimented several times for repreduction. and the code has also been merged into https://github.com/open-mmlab/mmdetection

**Comment by Hshuqin** [comment]
ok，thanks，I will try again
