### ISSUE TITLE
About the selection of positive and negative samples in the code

### ISSUE THREAD

**Issue by Hshuqin** [taokong/FoveaBox#8]
I have some confusion about the code.

in origin paper, two sigma is used to generate R_pos and R_neg separately, and the area between R_neg and R_pos is unassigned and will be ignored during training, is my understanding correct?

However, I see the code you posted. The positive sample definition only has a sigma = 0.4 , In which part of the definition code that ignores samples and negative samples is implemented?

Or is there a definition in the code for negative and ignored samples?

Or when you define a positive sample, do the points with a class label of 0 be used as negative samples for training?

thanks for answering

**Comment by taokong** [comment]
Thanks for your interests. We do not ignore samples in this implementation for simplicity.
