### ISSUE TITLE
deformable problem

### ISSUE THREAD

**Issue by alexwq100** [taokong/FoveaBox#9]
mmdet/ops/dcn/deform_conv.py", line 55, in forward
    cur_im2col_step)
RuntimeError: input image is smaller than kernel (shape_check at mmdet/ops/dcn/src/deform_conv_cuda.cpp:127)

when I  switch the with_deform=False, in the config file ,the above error reported, how to fix it ,thks

**Comment by taokong** [comment]
If you switch with_deform=False, the code should not call deformable ops.

**Comment by alexwq100** [comment]
sorry ,I mean true

**Comment by taokong** [comment]
you could also try the mmdetection version of FoveaBox 'https://github.com/open-mmlab/mmdetection/tree/master/configs/foveabox'
